/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EpExpand: typeof import('~icons/ep/expand')['default']
    EpFold: typeof import('~icons/ep/fold')['default']
    EpLocation: typeof import('~icons/ep/location')['default']
    EpMenu: typeof import('~icons/ep/menu')['default']
    ErrorPage: typeof import('./components/errorPage/index.tsx')['default']
    Header: typeof import('./components/layout/components/header.vue')['default']
    Icon: typeof import('./components/layout/components/icon.vue')['default']
    Layout: typeof import('./components/layout/index.vue')['default']
    Logo: typeof import('./components/layout/components/Sidebar/logo.vue')['default']
    Menu: typeof import('./components/layout/components/Sidebar/index.vue')['default']
    MenuItem: typeof import('./components/layout/components/menuItem.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/components/Sidebar/index.vue')['default']
  }
}
